services:
  - type: web
    name: netwatch
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -e .
      pip install -r requirements.txt
    startCommand: |
      cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: 10000 