services:
  - type: web
    name: netwatch
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -e .
    startCommand: |
      cd /opt/render/project/src && gunicorn --worker-class eventlet -w 1 --chdir /opt/render/project/src "wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: 10000 