services:
  - type: web
    name: netwatch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000 