services:
  - type: web
    name: netwatch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1 