services:
  - type: web
    name: netwatch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: FLASK_APP
        value: app.py
    staticPublishPath: ./netwatch/static 